[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url = sqlite:///./mlib.db

[core]
script_location = alembic_core
prepend_sys_path = .
sqlalchemy.url = sqlite:///./core.db

[music]
script_location = alembic_music
prepend_sys_path = .
sqlalchemy.url = sqlite:///./music.db

[movie]
script_location = alembic_movie
prepend_sys_path = .
sqlalchemy.url = sqlite:///./movie.db

[books]
script_location = alembic_books
prepend_sys_path = .
sqlalchemy.url = sqlite:///./books.db

[collections]
script_location = alembic_collections
prepend_sys_path = .
sqlalchemy.url = sqlite:///./collections.db

[games]
script_location = alembic_games
prepend_sys_path = .
sqlalchemy.url = sqlite:///./games.db

[wishes]
script_location = alembic_wishes
prepend_sys_path = .
sqlalchemy.url = sqlite:///./wishes.db

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
